url: https://peterkuma.net
collections:
  - article
  - presentation
  - poster
  - thesis
  - lecture
  - report
plugins:
  - jekyll-sitemap
cite_styles: [APA, Harvard, Chicago, AGU, AMetSoc, Copernicus]
cite_formats: [BibTeX, RIS, CSL-JSON]
cite_all: [APA, Harvard, Chicago, AGU, AMetSoc, Copernicus, BibTeX, RIS, CSL-JSON]
